tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
brew 'ant'
brew 'awscli'
brew 'curl'
brew 'gdbm'
brew 'git'
brew 'oniguruma'
brew 'jq'
brew 'libyaml'
brew 'mas'
brew 'openssl'
brew 'mysql'
brew 'node'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'ruby'
cask 'alfred2'
cask 'alinof-timer'
cask 'boostnote'
cask 'chatwork'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'intellij-idea'
cask 'iterm2'
cask 'java'
cask 'java7'
cask 'sourcetree'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
mas 'Keynote', id: 409183694
mas 'Pages', id: 409201541
mas 'Xcode', id: 497799835
mas 'Numbers', id: 409203825
